### ISSUE TITLE
Support description markdown

### ISSUE THREAD

**Issue by calebjacob** [near/near-discovery-components#146]
When documenting a component, we currently add a `x.metadata.json` file that has a `description` field. This field has to be escaped, so it's really tedious to write or modify when adding thorough documentation for a component.

Check out the following excerpt from the `DIG.Badge` documentation (note the `\n` characters and escaped `\"` quotes):

```
### Example\n\n```jsx\nreturn (\n  <Widget\n    src=\"near/widget/DIG.Badge\"\n
```

One solution would be supporting a new, optional `x.description.md` file. If present, this markdown file would be used to populate the metadata description when the CLI is publishing component changes. Should this feature be implemented in `bos-cli`?

**Comment by mpeterdev** [comment]
Yep, that would be a `bos-cli` change. I would submit an issue there: https://github.com/bos-cli-rs/bos-cli-rs

**Comment by calebjacob** [comment]
As an interim solution, feel free to use the helper component I created to edit `metadata.json` file descriptions: https://near.org/calebjacob.near/widget/MarkdownDescriptionEditor
