### ISSUE TITLE
[bug] "All" and "Following" Toggles not Working on Activity Feed

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery-components#325]
**Describe the bug**
Toggling between the "All" and "Following" filters on the activity feed is not rendering posts correctly. When I toggle to "Following" I still see content from all users and sometimes vice versa.

**To Reproduce**
1. Go to the activity feed
2. Click on "Following"
3. View Posts are incorrectly rendered

**Expected behavior**
- If a user has toggled "All" they should see posts from all users on near.org
- If a user has toggled "Following" they should see posts from only the users they follow

**Screenshots**
<img width="1512" alt="Screenshot 2023-09-13 at 2 47 07 PM" src="https://github.com/near/near-discovery-components/assets/129213007/fe1ec4a2-4766-423b-8e99-bd2658a81469">
<img width="1512" alt="Screenshot 2023-09-13 at 2 47 12 PM" src="https://github.com/near/near-discovery-components/assets/129213007/43d8792a-ce63-4a27-b9b6-4e8595074936">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Arc Browser
 - Version: Version 1.7.0 (41350)

**Smartphone (please complete the following information):**

**Additional context**
Multiple reports of this bug from other users.

**Comment by charleslavon** [comment]
@gabehamilton you might have some helpful insight on this issue if it's queryApi related
