### ISSUE TITLE
Comment on a comment is not shown anywhere

### ISSUE THREAD

**Issue by gabehamilton** [near/near-discovery-components#359]
**Describe the bug**
![Screenshot 2023-09-26 at 12 28 48 PM](https://github.com/near/near-discovery-components/assets/671506/a97543ab-cc4f-4374-a5b8-fb5e7439a12b)
Clicking on the comment's 'Add Comment' button and submitting a comment results in an on-chain [transaction](https://nearblocks.io/txns/9ePq3EbpRs5tXkqt7jtKt64svpuLykQuxL7poQtQYJ4r#execution) but the comment is not shown.

Commenting via the post's 'Add Comment' button does show up. [transaction](https://nearblocks.io/txns/FvfnKx3UqnDd7AKEBynzQVn69X9wrsYB7b9e4jYQNkv1#execution) 

**To Reproduce**
1. On near.org go to the post view of a post that has a comment, such as https://near.org/s/c?a=jlw.near&b=101847669
2. On one of the comments, click 'Add Comment'
3. Submit a comment
4. See that your comment does not appear even after reloading the page.

**Expected behavior**
A. Maybe comments should not have an 'Add Comment' option.
B. Comments on comments are displayed, nested below the comment they point to.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5.2 (22G91)
 - Browser Chrome
 - Version 117.0.5938.92 (Official Build) (arm64)

**Comment by charleslavon** [comment]
The issue seems to be that the UI is submitting a transaction which does not include the expected `key` to indicate where the post to which the comment belongs

**Comment by gabehamilton** [comment]
I think this is a duplicate of https://github.com/near/near-discovery/issues/740

Do we want nested comments like Near Social just added?
