### ISSUE TITLE
App Library Search Page with All Apps display

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/near-discovery-components#389]
**Is your feature request related to a problem? Please describe.**
We want to replace near.org/applications with the new App Library, however, currently there is no place for all apps to be shown since we have not have a real-time updated pipeline and will continue so for some time. 

**Impact**
near.org/applications is the most viewed page on near.org. This page serve as an activation channel for new users visiting near.org and major engagement channel for showcasing works on BOS. The current version is a gallery that is not user friendly, and this version has already received many positive feedbacks. Let's work to get this out ASAP so that more users can find cool apps to use on BOS. Thank you.

**Describe the solution you'd like**
We want to have the all apps display as a gallery in the order of most recently released under the SEARCH tab in the new App Library. 
We can simply use what we have right now in the current near.org/applications as below

![Screen Shot 2023-10-06 at 1 34 08 PM](https://github.com/near/near-discovery-components/assets/35774078/eb7e4b8e-39d5-496d-8d77-a9d304821db5)

**Describe alternatives you've considered**
We are working on a pipeline that updates it more frequently, however, it will be a bit far away from our release goal right now

**Additional context**
We hope this can be done and released as soon, target date to merge the new App Library to near.org/application is Oct 20 so this task should ideally be done by end of next week Oct 13th

**Comment by TiffanyGYJ** [comment]
**Engineering Estimate**
This is essentially just taking what we currently have on near.org/applications and put it into the Search section in the App Library. 
Cut down the 3 column to 2 column and have the search responsive as how it is. 

This should be less than 1h engineering work as a scope. 
@charleslavon @Ishatt @thisisjoshford @calebjacob 

I think there is a miscommunication on the scope of this ticket, this should be a S size in a small scope. 

Please let me know if this estimate is accurate and if this is something that can be tackle by Core team. Thank you.

cc @pkudinov

**Comment by calebjacob** [comment]
I don't think we want to actually pull in any code from the current `/applications` page. It sounds like we just need to update the new App Library search page to render all apps (with pagination) before a user enters a search query. This might take a few hours at most. The main work is updating the new App Library search page to support pagination via a "Load More" button.

**Comment by calebjacob** [comment]
If I end up having extra time this sprint, I'll let @charleslavon know and maybe we can pull this in.
