### ISSUE TITLE
Reduce number of HTTP calls on ActivityPage

### ISSUE THREAD

**Issue by calebjacob** [near/near-discovery-components#425]
The `ActivityPage` currently executes around 500 HTTP requests before it finishes loading. This is a ridiculous amount of requests and is a massive bottleneck for even modern browsers and high speed internet. On lower end devices or slower internet connections, this makes it almost unusable.

A lot of these requests are coming from nested components using things `Social.get()` and the `TimeAgo` component. We need to batch these requests or rely on Query API to provide this data as much as possible.

**Comment by charleslavon** [comment]
@calebjacob is this 500 request evaluation based on [the QueryAPI feed](https://github.com/near/near-discovery-components/blob/b64b389ea05fbbfc7c65c42026b62d58eabeceb3/src/Posts/Feed.jsx#L4). This feed has a trigger which defaults to the [previous Social.get() feed](https://github.com/near/near-discovery-components/blob/b64b389ea05fbbfc7c65c42026b62d58eabeceb3/src/v1/Posts.jsx#L1) in the event of problems with QueryAPI. 

@gabehamilton have I described that correctly?

**Comment by gabehamilton** [comment]
Correct if the blockheight difference between the QueryApi table the Social.index posts is greater than 2 it falls back. I think I've been seeing about 150 requests in the QueryApi version, plus plenty more with every scroll. Still definitely a problem, issue description is spot on in general.
