### ISSUE TITLE
Feeds should pull in profile fields via graphql relationships

### ISSUE THREAD

**Issue by gabehamilton** [near/near-discovery-components#427]
To improve the performance of the near.org feeds and reduce the number of data requests, the feed queries can fetch profile fields through new relationships to the accounts indexer.

Note, this Issue depends on #612 where the moderated_posts View moves into the `feed` indexer.

1. Create a hasura relationship between social_feed.posts and accounts.accounts tables. Create one between feed.moderated_posts and accounts.accounts. Determine whether to use foreign keys to create the relationships in the `feed` indexer's sql or to invoke hasura stored procedures.
2. Update the feed queries in PostsFeedControls.jsx to fetch profile fields: profile_name, profile_image, profile_tags using the account relationship.
3. Pass the profile fields through to the AccountProfile component (profile prop).

Note: Title and description updated Jan 16 2024

**Comment by charleslavon** [comment]
@shelegdmitriy is related to [885](https://github.com/near/near-discovery/issues/855)?

**Comment by shelegdmitriy** [comment]
> @shelegdmitriy is related to [885](https://github.com/near/near-discovery/issues/855)?

Not sure but could be... @gabehamilton could you please clarify this a bit?

**Comment by gabehamilton** [comment]
Yes, it's related to #885 and I'll rewrite the title and description of this ticket to match what we should do. This Issue got the notes about what fields we needed but we soon realized we needed the full account indexer. Now that we have that we can add relationships between social_feed.posts & accounts.accounts and feed.moderated_posts and accounts.accounts. That will allow the feed queries in PostsFeedControls to pull in the profile fields through the relationship.
