### ISSUE TITLE
Optimistically update UI when a new comment is submitted

### ISSUE THREAD

**Issue by calebjacob** [near/near-discovery-components#433]
Proposed Solution: Similar to how posts are optimistically updated, Optimistically update the feed UI with the user's comment after they submit a new comment.

Initial title was: Writing a comment to a post on the ActivityPage feed doesn't show up
If you write a comment on a post on the activity feed on `near.org` (the feed using Query API), it doesn't show up until you reload your browser. The comment should show up on your screen as soon as you post.

I'm going to assign this to @gabehamilton for now since you're probably most familiar with the Query API.

**Comment by charleslavon** [comment]
Once this task is ready for testing, we should retest [this issue](https://github.com/near/near-discovery-components/issues/359)  cc @AmmarHumackicSQA

**Comment by gabehamilton** [comment]
Code committed against this Issue will be foroptimistic updates for comments, #740 will be for updating the feed with new comments.

**Comment by charleslavon** [comment]
testing this is blocked by [this issue](https://github.com/near/near-discovery/issues/917)

**Comment by charleslavon** [comment]
Reopening as this doesn't appear to have been addressed when commenting on a comment.  After approving the transaction the UI is left in this editing state until I manually refresh the page. 
<img width="1159" alt="Screen Shot 2024-03-14 at 5 09 29 PM" src="https://github.com/near/near-discovery-components/assets/1915116/719a7222-90c9-4474-9326-ed61142add3a">
