### ISSUE TITLE
Edit / Fork Button lead to 404

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/near-discovery-components#458]
**Describe the bug**
The Edit / Fork button lead for 404 on the new component details page and the tab under develop menu

**To Reproduce**
1. Go to any component
2. click Edit/Fork

**Expected behavior**
Lands on Sandbox

**Screenshots**
![Screen Shot 2023-10-30 at 10 11 56 AM](https://github.com/near/near-discovery-components/assets/35774078/da50c5e2-e520-449a-8b1e-131125c283b7)
![Screen Shot 2023-10-30 at 10 23 38 AM](https://github.com/near/near-discovery-components/assets/35774078/3ae0cf0e-c845-4f30-b983-a7eb3bc62a9f)
![Screen Shot 2023-10-30 at 10 24 00 AM](https://github.com/near/near-discovery-components/assets/35774078/8d529fd4-a1a0-467f-b7fa-35373f590147)

**Desktop (please complete the following information):**
 - iOS
 - chrome

**Additional context**

**Comment by roshaans** [comment]
The fork button on this component also leads to a 404. 

![image](https://github.com/near/near-discovery-components/assets/25015977/52b63ef3-8df8-4293-bd5e-6263906b0942)
