### ISSUE TITLE
NearWeekNews components make excessive HTTP calls

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery-components#459]
**Is your feature request related to a problem? Please describe.**
The following two components would benefit from refactoring similar to what was accomplished [here](https://github.com/near/near-discovery-components/pull/429), to reduce HTTP requests and avoid triggering console errors/warning 

- nearweekapp.near/widget/NEARWEEKNews
- nearweekapp.near/widget/nearweek-newsletter

**Comment by charleslavon** [comment]
@AngelBlock could you please work on this issue?

**Comment by AngelBlock** [comment]
Sorry @calebjacob I missed last message, it should not make excessive calls, but let me look.
