### ISSUE TITLE
Inform the users whenever they are not allowed to use Fractal integration feature 

### ISSUE THREAD

**Issue by shelegdmitriy** [near/near-discovery-components#494]
**Is your feature request related to a problem? Please describe.**
At this moment user can add a couple of verification items at near.org/settings using the idOS SDK. To use idOS there are a couple of required items:

1. Wallet, with which user signed in, should support the `signMessage` method.
2. Wallet, with which user signed in, should be supported by [idos-sdk-js](https://github.com/idos-network/idos-sdk-js).

This means user who logged in with FastAuth will see the error.

**Describe the solution you'd like**
I'd like to see a banner or tooltip message to inform the user about which wallets does support both requirements.

**Additional context**
The list of supported wallets by [idos-sdk](https://github.com/idos-network/idos-sdk-js/blob/main/apps/idos-example-dapp/src/main.js#L73)
To check which wallet supports `signMessage` use this link [signMessage](https://near.org/signMessage)

**Comment by charleslavon** [comment]
Also show the info text without requiring a click, so it appears by default. The recommended wallets text can also appear here.

![Image](https://github.com/near/near-discovery-components/assets/1915116/f507b68f-7194-437c-bb58-ee4838dd18b7)
