### ISSUE TITLE
Hide, Report, Block of a user should stop notifications

### ISSUE THREAD

**Issue by gabehamilton** [near/near-discovery-components#570]
When a user chooses to Hide, Report, (or in future Block) a user that should also stop notifications from that user.

This should occur when a user chooses the Hide User (text is Mute username) or Report User menu items on a post, comment, or a user's profile.

![Screenshot 2023-12-13 at 10 31 56 AM](https://github.com/near/near-discovery-components/assets/671506/2a15957c-4696-4066-9eb1-1a13a02a0762)

**Comment by gabehamilton** [comment]
Yes, excluding hidden & reported user notifications for the hiding/reporting user and excluding moderated user notifications from all users could be done in the notifications indexer or the push notifications server. In either case it would require a query to the moderation_reporting and moderation_decisions [tables](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Fnear-queryapi.api.pagoda.co%2Fv1%2Fgraphql&header=x-hasura-role%3Adataplatform_near&query=query+MyQuery+%7B%0A++dataplatform_near_moderation_moderation_reporting%28limit%3A+10%29+%7B%0A++++base_content_account%0A++++base_content_blockheight%0A++++base_content_path%0A++++expiration%0A++++moderated_blockheight%0A++++moderated_path%0A++++notes%0A++++report_blockheight%0A++++moderated_account_id%0A++++label%0A++++group%0A++++account_id%0A++%7D%0A++dataplatform_near_moderation_moderation_decisions%28limit%3A+10%29+%7B%0A++++group%0A++++moderated_account_id%0A++++moderated_path%0A++++moderated_blockheight%0A++++moderator_account_id%0A++++label%0A++++expiration%0A++%7D%0A%7D%0A).

**Comment by milenakrawczyk** [comment]
Regarding the Web Push Notifications: We could also expose an endpoint to block a user in the notifications-server. Then clicking the _Mute user_ button would result in two separate calls: one to the moderation and another one to the notifications-server. The notifications-serverless-function would drop the notifications coming from the blocked user. This solution can be gateway-specific or non gateway-specific (global) depending on the implementation.

**Comment by charleslavon** [comment]
@erditkurteshiSQA building upon Milena's recommended path towards implementing support for block, we could leverage the notification server's [Preference API](https://github.com/near/notifications-server/blob/45719e12ea832a330be278dd9af31d7b806bac8c/src/preferences/preferences.service.ts#L15) to create [a Preference record](https://github.com/near/notifications-server/blob/45719e12ea832a330be278dd9af31d7b806bac8c/prisma/migrations/20231030115011_preferences/migration.sql#L8) to store the reporter's request along with an update to [processing of incoming notifications](https://github.com/near/notifications-serverless-function/blob/main/index.js#L134) to first check if a blocked preference applies before sending the notification. What are your thoughts on beginning to implement this approach?

**Comment by erditkurteshiSQA** [comment]
> @erditkurteshiSQA building upon Milena's recommended path towards implementing support for block, we could leverage the notification server's [Preference API](https://github.com/near/notifications-server/blob/45719e12ea832a330be278dd9af31d7b806bac8c/src/preferences/preferences.service.ts#L15) to create [a Preference record](https://github.com/near/notifications-server/blob/45719e12ea832a330be278dd9af31d7b806bac8c/prisma/migrations/20231030115011_preferences/migration.sql#L8) to store the reporter's request along with an update to [processing of incoming notifications](https://github.com/near/notifications-serverless-function/blob/main/index.js#L134) to first check if a blocked preference applies before sending the notification. What are your thoughts on beginning to implement this approach?

@charleslavon Based on what Milena suggested, I am aligned with the proposed approach and agree to continue. As I am gonna need some time for additional research and to gather more information, let me know when is the best time to proceed with this one for my side.

**Comment by charleslavon** [comment]
@erditkurteshiSQA please go ahead and proceed.
