### ISSUE TITLE
ProfilePage's contribution graph causes the display to jump

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery-components#609]
**Describe the bug**
On a desktop client, when viewing production near.org and then switching to the dev branch view of the profile page (via bos-loader), the page renders as expected for a moment, then the layout shifts due to the contribution widget taking the full width. 

How might this be avoided?

![profile](https://github.com/near/near-discovery-components/assets/1915116/aff4dc96-e3d0-4d9d-9bbb-5b3f30515b30)

**Comment by calebjacob** [comment]
Good catch! We had two separate PR's inflight at once that lead to this end result:

https://github.com/near/near-discovery-components/pull/597
https://github.com/near/near-discovery-components/pull/602

The combined changes lead to the wrapping problem you see. We just need to rework some of the CSS either in the profile page or the contribution component. Should be an easy fix.
