### ISSUE TITLE
Devhub Notifications are broken

### ISSUE THREAD

**Issue by Megha-Dev-19** [near/near-discovery-components#717]
- I recently added [PR](https://github.com/near/near-discovery-components/pull/692) to add support for different devhub notifications types, starting with `devhub/`, but it doesn't work as expected. 
I have a created a [video](https://wetransfer.com/downloads/81d464364214382356aa934db963d47a20240321143816/217111?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05) to explain the issue, the code also breaks for previously added `devgovgigs/` notifcations (on main branch) which worked fine previously.

**Comment by shelegdmitriy** [comment]
Hey @Megha-Dev-19. Thanks for filling this issue. I'm working on the solution for that. I have one question: why do you put a `notifier` [here](https://github.com/near/near-discovery-components/blob/develop/src/NearOrg/Notifications/utils.jsx#L127)? According to devhub [widget](https://near.social/mob.near/widget/WidgetSource?src=devhub.near/widget/devhub.notification.Left), which handles the link to proposal, they are not using a `notifier` field there. So, is that was just a typo from your side or there is some logic behind the `notifier` param?

**Comment by Megha-Dev-19** [comment]
hey @shelegdmitriy, yeah we don't need to pass it in params there.

**Comment by Megha-Dev-19** [comment]
`notifier` is the one who should be displayed as profile in notifications, since all the notifications will be created by `devhub.near` account but the actual person initiating it is the `notifier`, hope that makes sense.

**Comment by Megha-Dev-19** [comment]
@shelegdmitriy thank you for picking this, but there are still some issues

https://github.com/near/near-discovery-components/assets/100185149/2fcc4cc3-63a5-4fed-93dc-687a4f42deda

**Comment by shelegdmitriy** [comment]
> @shelegdmitriy thank you for picking this, but there are still some issues
> 
> 
> 
> https://github.com/near/near-discovery-components/assets/100185149/2fcc4cc3-63a5-4fed-93dc-687a4f42deda
> 
> 
> 
> 

Did you test it using the develop branch? That fix wasn't deployed into production yet

**Comment by Megha-Dev-19** [comment]
@shelegdmitriy Yeah I m checking on beta.near.org, that’s synced to develop right.?

**Comment by shelegdmitriy** [comment]
> @shelegdmitriy Yeah I m checking on beta.near.org, that’s synced to develop right.?

No it's not. You can check it locally using instructions

**Comment by shelegdmitriy** [comment]
Hey @Megha-Dev-19. Fix for this issue has been released on Friday, may I ask you to check how notifications works for you?

**Comment by Megha-Dev-19** [comment]
> > @shelegdmitriy Yeah I m checking on beta.near.org, that’s synced to develop right.?
> 
> No it's not. You can check it locally using instructions
In readme, it's mentioned here? is that wrong then.?
<img width="1209" alt="image" src="https://github.com/near/near-discovery-components/assets/100185149/42337a24-14ae-4171-95ae-443b2a94e081">

**Comment by Megha-Dev-19** [comment]
@shelegdmitriy I tried on production and there are still issues:
https://github.com/near/near-discovery-components/assets/100185149/f7b263d6-9e57-4756-a011-b64a36e3fe4d

**Comment by shelegdmitriy** [comment]
> @shelegdmitriy I tried on production and there are still issues:
> 
> https://github.com/near/near-discovery-components/assets/100185149/f7b263d6-9e57-4756-a011-b64a36e3fe4d
> 
> 
> 
> 

May I ask you to provide a clear examples of issues you have? Provide a screenshots how some notification looks on near.org vs near.social, and add a detailed example of the expected result so I'll have a clear view what I should fix.

**Comment by Megha-Dev-19** [comment]
@shelegdmitriy it doesn't work on near.social yet, the code isn't deployed there yet
in near.org: the text below the notification is wrong, it seems of some other notification, rather than the current one.

**Comment by shelegdmitriy** [comment]
Hey @Megha-Dev-19. I think, the issue you described here is relates to this one https://github.com/near/near-discovery/issues/909. FYI: I'm looking into it
